apiVersion: v1
kind: Service
metadata:
  name: web-server-app-service
spec:
  selector:
    app: web-server-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
  type: LoadBalancer